name: AutoPR

on:
  push:
    branches:
    - 'develop'

jobs:
  pull-request:
    name: 'Create PR'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      id: open-pr
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"                      # If blank, default: master
        pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
        pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
        pr_assignee: "Kanna727"                         # Comma-separated list (no spaces)
        pr_label: "auto-pr"                               # Comma-separated list (no spaces)
        github_token: ${{ secrets.MY_PAT }}
    - name: Enable Auto Merge
      if: ${{steps.open-pr.outputs.pr_url}}
      run: gh pr merge --auto --merge "${{steps.open-pr.outputs.pr_url}}"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}